### ISSUE TITLE
Unnecessarily removing double counting in mdlj.F90?

### ISSUE THREAD

**Issue by kmtu** [mtbys-lab/mcmdlj#1]
@Matubayasi , is [this line](https://github.com/mtbys-lab/mcmdlj/blob/f3831a807b73c697bd390445b66cf9b9dbfaebb5/mdlj.F90#L122) necessary?
```
stress(:, :, :) = stress(:, :, :) / 2.0    ! removing the double counting
```
What I see is that at [these lines](https://github.com/mtbys-lab/mcmdlj/blob/f3831a807b73c697bd390445b66cf9b9dbfaebb5/mdlj.F90#L107-L109) the double counting has already been excluded
```
    do i = 1, numpt - 1
       ...
       do j = i + 1, numpt
```
![latex-image-1](https://cloud.githubusercontent.com/assets/208968/13250435/42bc1c10-da6d-11e5-90a4-7d6925828300.png)

Did I miss anything?

**Comment by Matubayasi** [comment]
Yes, this line is necessary.
See Eqs (1) and (17) of the paper draft.
Although I use
    do i = 1, numpt - 1
       do j = i + 1, numpt
the sum is taken both for i and j.
And Eqs (1) and (17) means that the stress on each i is given by the sum over j and the sum needs to be divided by 2

**Comment by kmtu** [comment]
Ah, I see.
I mistakenly thought \sum_{i \neq j} is a double sum over i and j.
It actually is just sum over j.
Thank you.
